//    Exercicio 08 - Crie um algoritmo que receba 4 notas de um aluno e calcule a sua média.
//    Autor: Alessandro Ap. Antonio
//    Data: 09/03/2017
INICIO
    REAL n1 , n2 , n3 , n4 , media
    ESCREVER "Digite a nota 1: "
    LER n1
    ESCREVER "Digite a nota 2: "
    LER n2
    ESCREVER "Digite a nota 3: "
    LER n3
    ESCREVER "Digite a nota 4: "
    LER n4
    media <- ( n1 + n2 + n3 + n4 ) / 4
    escrever "A média é: " , media
FIM

